students={"mark":40,"maurice":50,"mary":80}
fruits={"Mango":30,"pineapples":80}
print(students)
print(fruits)
d1={('Hello,Hi'):"greetings"}
print(d1)
capitals={"Uganda":"kampala","Rwanda":"Kigali"}
k=capitals["Uganda"]
print(capitals["Burundi"])